HRDemoProject/Models/Department/DepartmentData.cs
namespace HRDemoProject.Models.Department
{
    public class DepartmentData
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }
}

HRDemoProject/Models/Employee/EmployeeData.cs
namespace HRDemoProject.Models.Employee
{
    using HRDemoProject.Models.Department;
    using HRDemoProject.Models.EmployeeStatus;

    public class EmployeeData
    {
        public int Id { get; set; }

        public string? FirstName { get; set; }

        public string? LastName { get; set; }

        public string? EmailAddress { get; set; }

        public DateTime? DateOfBirth { get; set; }

        public int DepartmentId { get; set; }

        public int EmployeeStatusId { get; set; }

        public string? EmployeeNumber { get; set; }

        public DepartmentData? Department { get; set; }

        public EmployeeStatusData? EmployeeStatus { get; set; }
    }
}

HRDemoProject/Models/Employee/EmployeeFilters.cs
namespace HRDemoProject.Models.Employee
{
    using HRDemoProject.Models.FilterOptions;
    using HRDemoProject.Response.Department;
    using HRDemoProject.Response.EmployeeStatus;

    public class EmployeeFilters
    {
        public EmployeeData EmployeeData { get; set; } = new EmployeeData();
        public DepartmentDataResponse DepartmentDataResponse { get; set; } = new DepartmentDataResponse();
        public EmployeeStatusDataResponse EmployeeStatusDataResponse { get; set; } = new EmployeeStatusDataResponse();
        public DataTableSettings DataTableSettings { get; set; } = new DataTableSettings();
    }
}

HRDemoProject/Models/EmployeeStatus/EmployeeStatusData.cs
namespace HRDemoProject.Models.EmployeeStatus
{
    public class EmployeeStatusData
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }
}

HRDemoProject/Models/ErrorViewModel.cs
namespace HRDemoProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HRDemoProject/Models/FilterOptions/DataTableSettings.cs
namespace HRDemoProject.Models.FilterOptions
{
    public class DataTableSettings
    {
        public int PageLength { get; set; } = 25;
    }
}

HRDemoProject/Controllers/EmployeeDataController.cs
namespace HRDemoProject.Controllers
{
    using HRDemoProject.Models.Employee;
    using HRDemoProject.Models.FilterOptions;
    using HRDemoProject.Services;
    using HRDemoProject.Services.Department;
    using HRDemoProject.Services.EmployeeData;
    using HRDemoProject.Services.EmployeeStatus;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    public class EmployeeDataController : Controller
    {
        private readonly ILogger<EmployeeDataController> _logger;
        private readonly IEmployeeDataService _employeeDataService;
        private readonly IDepartmentDataSerivce _departmentDataSerivce;
        private readonly IEmployeeStatusDataSerivce _employeeStatusDataSerivce;
        private readonly IConfiguration _configuration;

        public EmployeeDataController(
            ILogger<EmployeeDataController> logger,
            IEmployeeDataService employeeDataService,
            IDepartmentDataSerivce departmentDataSerivce,
            IEmployeeStatusDataSerivce employeeStatusDataSerivce,
            IConfiguration configuration)
        {
            _logger = logger;
            _employeeDataService = employeeDataService;
            _departmentDataSerivce = departmentDataSerivce;
            _employeeStatusDataSerivce = employeeStatusDataSerivce;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            var model = new EmployeeFilters()
            {
                DepartmentDataResponse = _departmentDataSerivce.GetFilteredDepartmentlistAsync().Result,
                EmployeeStatusDataResponse = _employeeStatusDataSerivce.GetFilteredDepartmentlistAsync().Result,
                DataTableSettings = new DataTableSettings()
                {
                    PageLength = Convert.ToInt32(_configuration["DataTableSettings:PageLength"]),
                }
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult GetFilteredData(int employeeStatusId, int departmentId)
        {
            var filteredEmployees = _employeeDataService.GetFilteredEmployeeListAsync(null, employeeStatusId, departmentId).Result;
            return Json(filteredEmployees.EmployeeDataList);
        }

        [HttpPost]
        public IActionResult CreatEmployeeData()
        {
            var model = new EmployeeFilters()
            {
                DepartmentDataResponse = _departmentDataSerivce.GetFilteredDepartmentlistAsync().Result,
                EmployeeStatusDataResponse = _employeeStatusDataSerivce.GetFilteredDepartmentlistAsync().Result,
                DataTableSettings = new DataTableSettings()
                {
                    PageLength = Convert.ToInt32(_configuration["DataTableSettings:PageLength"]),
                }
            };

            return PartialView("_CreateEditEmployeeData", model);
        }

        [HttpPost]
        public IActionResult EditEmployeeData(int employeeId)
        {
            var employees = _employeeDataService.GetFilteredEmployeeListAsync(employeeId, null, null).Result;

            var model = new EmployeeFilters()
            {
                EmployeeData = employees.EmployeeDataList.FirstOrDefault() ?? new EmployeeData(),
                DepartmentDataResponse = _departmentDataSerivce.GetFilteredDepartmentlistAsync().Result,
                EmployeeStatusDataResponse = _employeeStatusDataSerivce.GetFilteredDepartmentlistAsync().Result,
                DataTableSettings = new DataTableSettings()
                {
                    PageLength = Convert.ToInt32(_configuration["DataTableSettings:PageLength"]),
                }
            };

            return PartialView("_CreateEditEmployeeData", model);
        }

        [HttpPost]
        public async Task<IActionResult> SaveEmployeeData(EmployeeData employeeData)
        {
            var result = new Result();

            if (employeeData.Id == 0)
            {
                result = await _employeeDataService.CreateEmployeeDataAsync(employeeData);
                _logger.LogInformation($"SaveEmployeeData Create isSuccess:{result.IsSuccess}|isFailure:{result.IsFailure}|Code:{result.Code}|Message:{result.Message}");
            }
            else
            {
                result = await _employeeDataService.UpdateEmployeeDataAsync(employeeData);
                _logger.LogInformation($"SaveEmployeeData Update Id:{employeeData.Id}|isSuccess:{result.IsSuccess}|isFailure:{result.IsFailure}|Code:{result.Code}|Message:{result.Message}");
            }

            return Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteEmployeeData(int employeeId)
        {
            var result = new Result();
            result = await _employeeDataService.DeleteEmployeeDataAsync(new EmployeeData() { Id = employeeId });
            _logger.LogInformation($"DeleteEmployeeData Id:{employeeId}|isSuccess:{result.IsSuccess}|isFailure:{result.IsFailure}|Code:{result.Code}|Message:{result.Message}");
            return Json(result);
        }
    }
}

HRDemoProject/Controllers/ErrorController.cs
namespace HRDemoProject.Controllers
{
    using HRDemoProject.Models;
    using Microsoft.AspNetCore.Mvc;
    using System.Diagnostics;

    public class ErrorController : Controller
    {
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Index()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HRDemoProject/Views/EmployeeData/Index.cshtml
@{
    ViewData["Title"] = "Employee Data";
    var pageLength = Model.DataTableSettings.PageLength;
}

<div class="container mt-4">
    <div class="row mb-3">
        <div id="divMessages"></div>
    </div>
    <div class="row mb-3">
        <div class="col-md-11">
            <label for="statusFilter">Employee Data</label>
        </div>
        <div class="col-md-1">
            <button class="btn btn-primary" onclick="openEmployeeModalCreateEdit()">Add</button>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-md-6">
            <label for="statusFilter">Filter by Status:</label>
            <select id="employeeStatusFilter" class="form-control">
                <option value="">All</option>
                @foreach (var employeeStatus in Model.EmployeeStatusDataResponse.EmployeeStatusList)
                {
                    <option value="@employeeStatus.Id">@employeeStatus.Name</option>
                }
            </select>
        </div>
        <div class="col-md-6">
            <label for="departmentFilter">Filter by Department:</label>
            <select id="departmentFilter" class="form-control">
                <option value="">All</option>
                @foreach (var department in Model.DepartmentDataResponse.DepartmentDataList)
                {
                    <option value="@department.Id">@department.Name</option>
                }
            </select>
        </div>
    </div>
    <table id="tblEmployeeData" class="table table-striped table-bordered" style="width:100%">
        <thead class="thead-light">
            <tr>
                <th class="text-left"></th>
                <th class="text-left">First Name</th>
                <th class="text-left">Last Name</th>
                <th class="text-left">Date of Birth</th>
                <th class="text-left">Department Name</th>
                <th class="text-left">Status</th>
                <th class="text-left">Employee Number</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

<div class="modal fade" id="employeeModal" tabindex="-1" role="dialog" aria-labelledby="employeeModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="employeeModalLabel"></h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="max-height: calc(100vh - 210px); overflow-y: auto;">
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    Are you sure you want to delete this employee?
                </div>
                <div class="mb-3">
                    <label for="FirstName" class="form-label">First Name:</label>
                    <input type="text" class="form-control" id="txtDeleteFirstName" name="FirstName" />
                </div>
                <div class="mb-3">
                    <label for="LastName" class="form-label">Last Name:</label>
                    <input type="text" class="form-control" id="txtDeleteLastName" name="LastName" />
                </div>
                <div class="mb-3">
                    <label for="EmployeeNumber" class="form-label">Employee Number:</label>
                    <input type="text" class="form-control" id="txtDeleteEmployeeNumber" name="EmployeeNumber" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" id="confirmDelete">Delete</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>

        $(document).ready(function () {
            GetFilteredData();
        });

        $('#employeeStatusFilter').change(function () {
            GetFilteredData();
        });

        $('#departmentFilter').change(function () {
            GetFilteredData();
        });

        function GetFilteredData() {
            $.ajax({
                url: '@Url.Action("GetFilteredData", "EmployeeData")',
                type: 'POST',
                data: {
                    employeeStatusId: $("#employeeStatusFilter option:selected").val(),
                    departmentId: $("#departmentFilter option:selected").val()
                },
                dataType: "json",
                success: function (response) {
                    BindGridData(response);
                }
            });
        }
        
        function BindGridData(filteredData) {
            $('#tblEmployeeData').DataTable().clear().destroy();
            $('#tblEmployeeData').DataTable({
                responsive: true,
                bLengthChange: true,
                lengthMenu: [[5, 10, 25, 50, 75, 100, -1], [5, 10, 25, 50, 75, 100, "All"]],
                bFilter: true,
                bSort: true,
                bPaginate: true,
                pageLength: @pageLength,
                data: filteredData,
                columns: [
                    {
                        data: 'id',
                        render: function (data, type, row) {
                            return '<a href="#" class="btn btn-primary" onclick="openEmployeeModalCreateEdit(' + data + ')">Edit</a>' +
                                   ' <a href="#" class="btn btn-danger" onclick="openDeleteModal(' + data + ', \'' + row.firstName + '\', \'' + row.lastName + '\', \'' + row.employeeNumber + '\')">Delete</a>';
                        },
                        width: "150px"
                    },
                    { data: 'firstName' },
                    { data: 'lastName' },
                    {
                        data: 'dateOfBirth',
                        render: function (data, type, row) {
                            var date = new Date(data);
                            var day = ("0" + date.getDate()).slice(-2);
                            var month = ("0" + (date.getMonth() + 1)).slice(-2);
                            var year = date.getFullYear();
                            return day + "/" + month + "/" + year;
                        }
                    },
                    { data: 'department.name' },
                    { data: 'employeeStatus.name' },
                    { data: 'employeeNumber' }
                ]
            });
        }

        function openEmployeeModalCreateEdit(employeeId) {
            if(employeeId == null)
            {
               $.ajax({
                    url: '@Url.Action("CreatEmployeeData", "EmployeeData")',
                    type: 'POST',
                    dataType: "HTML",
                    success: function (response) {
                        $('#employeeModalLabel').text('Create Employee');
                        $('#employeeModal .modal-body').html(response);
                        $('#employeeModal').modal('show');
                    }
                });
            }
            else
            {
               $.ajax({
                    url: '@Url.Action("EditEmployeeData", "EmployeeData")',
                    type: 'POST',
                    data: {
                        employeeId: employeeId
                    },
                    dataType: "HTML",
                    success: function (response) {
                        $('#employeeModalLabel').text('Edit Employee');
                        $('#employeeModal .modal-body').html(response);
                        $('#employeeModal').modal('show');
                    }
                });
            }
        }

        function openDeleteModal(employeeId, firstName, lastName, employeeNumber) {
            $('#txtDeleteFirstName').val(firstName);
            $('#txtDeleteLastName').val(lastName);
            $('#txtDeleteEmployeeNumber').val(employeeNumber);
            $('#deleteModal').modal('show');
            $('#confirmDelete').off('click').on('click', function () {
                deleteEmployee(employeeId);
                $('#deleteModal').modal('hide');
            });
        }

        function deleteEmployee(employeeId) {
            $.ajax({
                url: '@Url.Action("DeleteEmployeeData", "EmployeeData")',
                type: 'POST',
                data: {
                    employeeId: employeeId
                },
                dataType: "json",
                success: function (response) {
                    if (response.isSuccess == true) {
                        var alertDiv = $('<div class="alert alert-success fade show" role="alert">')
                            .text('Employee has successfully been deleted')
                        $('#divMessages').html(alertDiv);
                        GetFilteredData();
                    }
                    else {
                        var alertDiv = $('<div class="alert alert-danger fade show" role="alert">')
                            .text('Error deleting employee data: ' + response.message)
                        $('#divMessages').html(alertDiv);
                    }
                }
            });
        }
    </script>
}

HRDemoProject/Views/EmployeeData/_CreateEditEmployeeData.cshtml
@model HRDemoProject.Models.Employee.EmployeeFilters

<div class="container">
    <form class="needs-validation" novalidate>
        <input type="hidden" id="hdnId" name="Id" value="@Model.EmployeeData.Id" />
        <div class="mb-3 text-center">
            <div id="divResult"></div>
        </div>
        <div class="mb-3">
            <label for="FirstName" class="form-label">First Name:</label>
            <input type="text" class="form-control" id="txtFirstName" name="FirstName" value="@Model.EmployeeData.FirstName" placeholder="First Name" required  />
            <div class="invalid-feedback">First name is required</div>
        </div>
        <div class="mb-3">
            <label for="LastName" class="form-label">Last Name:</label>
            <input type="text" class="form-control" id="txtLastName" name="LastName" value="@Model.EmployeeData.LastName" placeholder="Last Name" required />
            <div class="invalid-feedback">Last name is required</div>
        </div>
        <div class="mb-3">
            <label for="EmailAddress" class="form-label">Email Address:</label>
            <input type="email" class="form-control" id="txtEmailAddress" name="EmailAddress" value="@Model.EmployeeData.EmailAddress" placeholder="Email Address" required />
            <div class="invalid-feedback">Valid email address is required</div>
        </div>
        <div class="mb-3">
            <label for="DateOfBirth" class="form-label">Date of Birth:</label>
            <input type="date" class="form-control" id="txtDateOfBirth" name="DateOfBirth" value="@Model.EmployeeData.DateOfBirth?.ToString("yyyy-MM-dd")" placeholder="Date of Birth" required max="@DateTime.Now.AddYears(-16).ToString("yyyy-MM-dd")" />
            <div class="invalid-feedback">Enter a valid date of birth, cannot be in the future and minimum 16 years old</div>
        </div>
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                var dateOfBirthInput = document.getElementById('txtDateOfBirth');
                var today = new Date();
                var maxDate = new Date(today.getFullYear() - 16, today.getMonth(), today.getDate());
                dateOfBirthInput.max = maxDate.toISOString().split('T')[0];
            });
        </script>
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                var dateOfBirthInput = document.getElementById('txtDateOfBirth');
                var today = new Date();
                var maxDate = new Date(today.getFullYear() - 18, today.getMonth(), today.getDate());
                dateOfBirthInput.max = maxDate.toISOString().split('T')[0];
            });
        </script>
        <div class="mb-3">
            <label for="DepartmentId" class="form-label">Department:</label>
            <select id="ddlDepartment" class="form-control" name="DepartmentId" required>
                @if (@Model.EmployeeData.Id != 0)
                {
                    @foreach (var department in Model.DepartmentDataResponse.DepartmentDataList)
                    {
                        <option value="@department.Id" selected="@(department.Id == Model.EmployeeData.DepartmentId)">@department.Name</option>
                    }
                }
                else
                {
                    @foreach (var department in Model.DepartmentDataResponse.DepartmentDataList)
                    {
                        <option value="@department.Id">@department.Name</option>
                    }
                }
            </select>
            <div class="invalid-feedback">Department is required</div>
        </div>
        <div class="mb-3">
            <label for="EmployeeStatusId" class="form-label">Employee Status:</label>
            <select id="ddlEmployeeStatus" class="form-control" name="EmployeeStatusId" required>
                @if (@Model.EmployeeData.Id != 0)
                {
                    @foreach (var employeeStatus in Model.EmployeeStatusDataResponse.EmployeeStatusList)
                    {
                        <option value="@employeeStatus.Id" selected="@(employeeStatus.Id == Model.EmployeeData.EmployeeStatusId)">@employeeStatus.Name</option>
                    }
                }
                else
                { 
                    @foreach (var employeeStatus in Model.EmployeeStatusDataResponse.EmployeeStatusList)
                    {
                        <option value="@employeeStatus.Id">@employeeStatus.Name</option>
                    }
                }
            </select>
            <div class="invalid-feedback">Employee Status is required</div>
        </div>
        <div class="mb-3">
            <label for="EmployeeNumber" class="form-label">Employee Number:</label>
            <input type="text" class="form-control" id="txtEmployeeNumber" name="EmployeeNumber" value="@Model.EmployeeData.EmployeeNumber" required placeholder="Employee Number" />
            <div class="invalid-feedback">Employee Number is required</div>
        </div>
        <div class="mb-3">
            <div class="d-flex justify-content-between">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="reloadGrid()">Cancel</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </form>
</div>

<script>
    (function () {
        'use strict'
        var forms = document.querySelectorAll('.needs-validation')
        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    } else {
                        event.preventDefault();
                        saveEmployeeChanges();
                    }
                    form.classList.add('was-validated')
                }, false)
            })
    })()

    function saveEmployeeChanges() {
        var employeeData = {
            id: $('#hdnId').val(),
            firstName: $('#txtFirstName').val(),
            lastName: $('#txtLastName').val(),
            emailAddress: $('#txtEmailAddress').val(),
            dateOfBirth: $('#txtDateOfBirth').val(),
            departmentId: $("#ddlDepartment option:selected").val(),
            employeeStatusId: $("#ddlEmployeeStatus option:selected").val(),
            employeeNumber: $('#txtEmployeeNumber').val(),
        };

        $.ajax({
            url: '@Url.Action("SaveEmployeeData", "EmployeeData")',
            type: 'POST',
            data: employeeData,
            dataType: "json",
            success: function (response) {
                if(response.isSuccess == true)
                {
                    var alertDiv = $('<div class="alert alert-success fade show" role="alert">')
                            .text('Success saving employee data')
                            $('#divResult').html(alertDiv);
                            
                    reloadGrid();

                }
                else
                {
                    var alertDiv = $('<div class="alert alert-danger fade show" role="alert">')
                            .text('Error saving employee data: ' + response.message)
                            $('#divResult').html(alertDiv);
                }
            }
        });
    }

    function reloadGrid(){
        setTimeout(function() {
            $('#employeeModal').modal('hide');
            GetFilteredData();
        }, 2000);
    }
</script>

HRDemoProject/Views/Shared/_Layout.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HR Demo Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HRDemoProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - HR Demo Project</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>